# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18NBF4mUcjScZJqnv63RojTIsyiO5qFlG
"""

from flask import Flask, request, render_template_string
import pandas as pd
import re
from nltk.sentiment import SentimentIntensityAnalyzer
import nltk

# Télécharger les ressources nécessaires NLTK
nltk.download('vader_lexicon')

# Initialiser l'application Flask
app = Flask(__name__)

# Charger le dataset
df = pd.read_csv('Reviews.csv')

# Initialiser VADER
sia = SentimentIntensityAnalyzer()

# Fonction de nettoyage du texte
def clean_text(text):
    # Supprimer les caractères spéciaux et mettre en minuscules
    text = re.sub(r'[^\w\s]', '', text.lower())
    return text

# Route principale
@app.route('/', methods=['GET', 'POST'])
def index():
    sentiment = None
    if request.method == 'POST':  # Vérifie si un avis est soumis via POST
        review = request.form['review']  # Récupérer le texte de l'avis

        # Nettoyer l'avis
        cleaned_review = clean_text(review)

        # Analyser le sentiment avec VADER
        sentiment_scores = sia.polarity_scores(cleaned_review)  # Obtenir les scores de sentiment
        sentiment_value = sentiment_scores['compound']  # Score de sentiment global

        # Déterminer le sentiment
        if sentiment_value >= 0.05:
            sentiment = 'positive'
        elif sentiment_value <= -0.05:
            sentiment = 'negative'
        else:
            sentiment = 'neutral'

    # Code HTML pour l'interface utilisateur
    return render_template_string(f'''
    <!DOCTYPE html>
    <html lang="fr">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Sentiment Analyzer</title>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    background-color: #f5f5f5;
                    color: #febd69;
                    text-align: center;
                    padding: 20px;
                }}
                h1 {{
                    color: #132f8c;
                }}
                textarea {{
                    width: 80%;
                    height: 100px;
                    margin: 10px 0;
                    padding: 10px;
                    font-size: 16px;
                    border: 1px solid #ddd;
                    border-radius: 5px;
                }}
                input[type="submit"] {{
                    padding: 10px 20px;
                    font-size: 16px;
                    background-color: #febd69;
                    color: white;
                    border: none;
                    border-radius: 5px;
                    cursor: pointer;
                }}
                input[type="submit"]:hover {{
                    background-color: #febd69;
                }}
                h2 {{
                    margin-top: 20px;
                    color: #132f8c;
                }}
                img {{
                    max-width: 150px;
                    margin-bottom: 20px;
                }}
                h3 {{
                    color: #febd69;
                }}
            </style>
        </head>
        <body>

            <h1>Sentiment Analyzer for amazon reviews</h1>
            <form method="POST">
                <textarea name="review" placeholder="What do you think of the product?"></textarea><br>
                <input type="submit" value="Analyze">
            </form>
            <h2>Your review is : <h3>{sentiment if sentiment else ""}</h3></h2>
        </body>
    </html>
    ''')

# Lancer l'application Flask
if __name__ == '__main__':
    app.run(debug=True)